### ISSUE TITLE
connect() got an unexpected keyword argument 'use_ssl'

### ISSUE THREAD

**Issue by sanctusmob** [Mathzx/zxLoLBoT#12]
When i run the hello.py i get this error

python3 hello.py 

Traceback (most recent call last):
  File "hello.py", line 16, in <module>
    bot.connect()
  File "/root/lolbot/zxlolbot.py", line 279, in connect
    if self.xmpp.connect((str(serverIp[0]), self.port), use_ssl=True):
TypeError: connect() got an unexpected keyword argument 'use_ssl'

**Comment by sanctusmob** [comment]
I resolve problem by installing the latest version of sleekxmpp (1.3.1)
